### ISSUE TITLE
iNotifyTree fails to start.

### ISSUE THREAD

**Issue by russel** [DmitryOlshansky/dinotify#10]
I am finding that on Debian Sid:
```d
auto inotifyTree = iNotifyTree("/dev/", IN_CREATE | IN_DELETE);
```
is hanging. Any idea what circumstances might cause this?

Maybe not a block, I waited long enough and:
```
Failed to stat file `/dev/fd/13/fd/13/fd/13/fd/13/fd/13/fd/13/fd/13/fd/13/fd/13/fd/13/fd/13/fd/14/14/14/36/25/shm/org.chromium.nXl0GH'
```
which is definitely a "WTF".

**Comment by DmitryOlshansky** [comment]
Symbolic links...
Need a flag not to follow symlinks

**Comment by DmitryOlshansky** [comment]
Second problem with /dev is to have the right permissions. Ideally you should watch as narrow as possible.

Maybe I should just add ability to add directories recursively to iNotify instead.

**Comment by russel** [comment]
I really want to watch /dev/dvb only, however it seems not possible to put a watch on a non-existent directory. Rust Notify seems have found a way round this, but DInotify and FSWatch appearnot to have. I guess I can revert to the two phase strategy of watching Dev for the creation of /dev/dvb and then do a recursive watch on that.

**Comment by DmitryOlshansky** [comment]
I really should fix this. Just add a print to both of `add` functions and tell me what it prints. A few pages worth of output would be enough. Then I'll know if it's stuck in some symlink loop of sorts.

The proper solution is to keep a hash table of visited inodes, I'll try it once I confirm it's symlink problem.

**Comment by russel** [comment]
I believe this is the data you were asking for.

[me-tv_output.txt](https://github.com/DmitryOlshansky/dinotify/files/2026349/me-tv_output.txt)

**Comment by DmitryOlshansky** [comment]
Finally got around to fixing this, see v0.5.0 as the first version where iNotify with /dev works
