### ISSUE TITLE
Avoid gh-pages branch, use master branch for docs?

### ISSUE THREAD

**Issue by russel** [DmitryOlshansky/dinotify#11]
It is no longer necessary to have a gh-pages branch for website documentation, it can be in a directory in the master branch. Personally I never used gh-pages exactly because it was a branch, but when it became a directory in master, I feel it is usable. But this is a personal opinion of course.

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by DmitryOlshansky** [comment]
Sorry but I cannot be bothered with stuff like that. I do not really care as CI does all the heavy lifting anyway and 100% of docs is generated. I see very few reasons to add dead generated weight to master.
