### ISSUE TITLE
Inotify.read has no timeout form

### ISSUE THREAD

**Issue by russel** [DmitryOlshansky/dinotify#7]
It appears that `Inotify.read` is a blocking read with no option for a timeout. Should there be a variant with a timeout, or is there a known idiom for terminating a thread blocked in an `Inotify.read` call?

**Comment by DmitryOlshansky** [comment]
Closing the file should do it.
Basically adding a close method should fix this.

**Comment by russel** [comment]
I am being slow I fear, I am watching the /dev/dvb directory and /dev/dvb/adaptor* directories, at no time am I actually opening a file within the listener thread I am using to create "newly created" and "removed" messages. I am not sure closing a file is an option.

**Comment by russel** [comment]
It seems that an inotify file descriptor can be used with select, poll, or epoll, to provide a way of blocking on a read being possible but with a timeout, i.e. only do the read when there is something to be read. I guess the question is whether to construct a D binding to these C functions in this package or elsewhere, or whether to write a timeout read in this D package using these C functions.

**Comment by DmitryOlshansky** [comment]
I meant closing file descriptor of inotify)
Anyway yes a timeout could be easily supplied by using poll function.
We have bindings for poll, so I’ll conjure a version of read with timeout.

**Comment by russel** [comment]
Sadly the file descriptor isn't available to close from outwith the class.

epoll rather than poll?

I am entirely willing and able to help create a `read_with_timeout`.

**Comment by russel** [comment]
This ends up effectively being a replica of Issue #8 . This has now been solved by changeset d945cec
