### ISSUE TITLE
Updating the API

### ISSUE THREAD

**Issue by russel** [DmitryOlshansky/dinotify#8]
It seems:

DInitify doesn't cover full capabilities of the inotify API.
Especially it doesn't utilize newer inotify_init1 syscall and 
doesn't expose 'select' interface.
This C++ wrapper may be interesting for you: 
https://github.com/erikzenker/inotify-cpp
But I haven't used it.

as reported by Arek on the DMD Learn email list. I'll investigate and see if I can create a pull request.

**Comment by russel** [comment]
Since the fd field is private in the struct INotify, it would appear that the way forward is one of:

– add a `read_timeout` method, and deal with using `epoll` within this method.

– add a `wait_for_readable_timeout`, and deal with using `epoll` within this method.

– add a getter for the fd so that any `epoll` stuff is done outside of the inotify module.

**Comment by DmitryOlshansky** [comment]
I think we can do 2 things:
- expose fd
- add timeout to read (simple poll is fine for 1 fd)
- the flags passed to inotify_init1 are 2 things: close on exec and nonblocking. Nonblocking will be added to satisfy timeout interface. The 2nd flag at best saves on 1 syscall  to fcntl so dunno how useful is that. (~100ns per inotify, but you likely need only 1 inotify)

**Comment by DmitryOlshansky** [comment]
PS. Gotta love the off by one errors

**Comment by russel** [comment]
Exposing the fd allows for the select/poll/epoll to be "someone else's problem", but breaks the encapsulation of the abstraction of the INotify class. Obviously a read only getter for the fd ameliorates this.

Adding a timeout to the read or providing a second read with a timeout leaving the original read as is, seems like the right way since many other API have the "blocking read" and "blocking read with timeout" approach.

I can find core.sys.linux.epoll but nothing for select or poll, so I had assumed epoll was the preferred choice. But just checking for one fd means all are equally efficient, so choose the nicest on to work with.

If the read can be made non-blocking then I can implement a busy wait loop, but this seems wrong when the kernel can provide the wait by processing events. Or maybe just a busy wait using a sleep is fine.

**Comment by DmitryOlshansky** [comment]
Long story short - epoll is for heavy-duty things where the cost of passing a set of FDs to the kernel is high. For single FD poll is the ticket.

Anyhow checkout the latest commits / v0.3.0. I do not build meson build so check it out. It also exposes FD as dscriptor for when you want to get down and dirty or just integrate with your own epoll eventloop.

P.S. Did an accidental force push... Hopefully all your commits restored, please check it as well.

**Comment by DmitryOlshansky** [comment]
And poll is in core.sys.posix.poll ;)

**Comment by russel** [comment]
I patched my forks of the repository so no problem. It seems v0.3.0 builds and, at first sight, works as required. More after further experiments.

Thanks for this, it has unblocked my progress.
