### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by aberba** [DmitryOlshansky/dinotify#9]
Can you please show a demo of using this lib?

**Comment by russel** [comment]
My usage is in this file:

https://github.com/Russel/Me-TV_D/blob/master/source/inotify_daemon.d

I am not using the INotifyTree feature of dinotify as I am creating a simple state machine to monitor as little as possible. But I may be doing this wrong overly influenced by the underlying C API.

[Update after experience with Rust INotify and then switching to Rust Notify, I think my D code may be way over-complicated!]

**Comment by DmitryOlshansky** [comment]
3 month. OMG, gotta check my notification settings...

Will add some today-tomorrow.

**Comment by DmitryOlshansky** [comment]
Then I realize there is already a documented unittest for both primitives. I’d add gh-pages to show the docs then.

**Comment by DmitryOlshansky** [comment]
Did my best given how strange ddox works compared to simple ddoc I'm used to in Phobos.
So I put both examples in README and a link to ddox pages.
